### ISSUE TITLE
How to append data from list or array

### ISSUE THREAD

**Issue by slartz42** [domarm-comat/pglive#23]
Hello,

First off I just want to say this package has been extremely useful, thanks to whoever put this together!

Is there a way to use cb_append_data_point with a list or array? I found cb_set_data works with lists, but I would like retain the existing data in the window similar to how to append_data_point function works.

So far I have tried iterating over the list with a for loop and appending each individual item, but the plot still only shows one value from the list. Any suggestions?

**Comment by domarm-comat** [comment]
Hey! I'm happy you find this package useful.

Currently there are only those two options you mentioned. But I can definitely see, that being able to append array / list can be really helpful. I will have a look and try to implement it soon. I will get back to you once it's ready :). I hope it won't take longer than few days.

**Comment by slartz42** [comment]
Ok great, thanks!

**Comment by domarm-comat** [comment]
I've got some time and it turns out it was not that difficult to implement array append. Please try to pull `cb_append_data_array` branch. You can find new `DataConnector.cb_append_data_array` method there.
Ones you confirm, that it does what you need, I will merge it into main branch.

You can also try `sin_wave_array_generator`, `candle_array_generator` or `category_array_generator` in provided examples.

**Comment by slartz42** [comment]
That's perfect, it's working for me

**Comment by domarm-comat** [comment]
Great, then I will close this issue and merge changes into main branch.
