### ISSUE TITLE
X and Y  axis display scientific notation when value is zero and range contiues to increase.

### ISSUE THREAD

**Issue by optio50** [domarm-comat/pglive#9]
Version 0.5.2

If I start my program and the current values are zero, the X and Y axis displays in scientific notation wheres the older version did not exhibit this trait.

It takes a few minuets (2 or 3) at a 1hz rate but the range just keeps increasing in both the positive and negative direction.

 
Old 0.3.3
![0 3 3_Version](https://user-images.githubusercontent.com/4461936/195514925-8eb65a14-0f19-469e-b9c6-20fe9e7e6e50.png)

New 0.5.2
![0 5 2_Version](https://user-images.githubusercontent.com/4461936/195518539-15a17c33-12ac-48fd-ab2f-ed1389fd8570.png)

~~I think the chart may correct with fresh values that are not zero but I thought you may find this report helpful.~~

Well, it seems to be happening with larger values as well. The autorange seems to be in a increasing runaway mode.

**Comment by domarm-comat** [comment]
Another great bug discovery! Thanks a lot for your patience and testing. This issue was again related to the new LiveAxis feature. It seems that PyqtGraph doesn't like when min and max value of either X or Y axis is the same value. I did a simple fix by subtracting 0.4 from min and adding 0.4 to max when min == max.
Please give v0.5.3 a try and see if that fixes your issue.

**Comment by optio50** [comment]
All seems to be working correctly.

You're pretty cool. :-) Thanks for taking the time to fix these things so quickly. I know you work hard and are busy.
